"""Add expense approval request columns

Revision ID: c05def236b97
Revises: e0cd5caa2aac
Create Date: 2025-12-25 19:00:21.383281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c05def236b97'
down_revision = 'e0cd5caa2aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('request_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('request_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('request_data')
        batch_op.drop_column('request_reason')
        batch_op.drop_column('request_type')

    # ### end Alembic commands ###
